VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/main.yml"
    ansible.limit = "192.168.2.100"
    ansible.inventory_path = "../../ansible/inventory/hosts"
    ansible.sudo = true
  end

  config.vm.network "public_network", ip: "192.168.2.100", bridge: "wlan0"
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
end
