Vagrant.configure("2") do |config|
  #config.ssh.private_key_path = "/usr/share/vagrant/keys/vagrant"
  #config.ssh.port = "2222"
  config.ssh.username = "vagrant"
  config.vm.define "a"
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/main.yml"
    ansible.limit = "192.168.2.100"
    ansible.inventory_path = "../../ansible/inventory/hosts"

  end

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "public_network", ip: "192.168.2.100", bridge: "wlan0"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
end
