VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..5).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.box = "debian/jessie64"
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../../ansible/main.yml"
        ansible.limit = "docker"
        ansible.inventory_path = "../../../ansible/inventory/hosts"
        ansible.sudo = true
      end
      node.vm.network "public_network", ip: "192.168.2.11#{i}", bridge: "wlan0"
      node.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
      end
    end
  end
end
