---
- hosts: webservers
  handlers:
    - name: "restart apache2"
      service: name=apache2 state=restarted

  tasks:
    - name: "Ensure apache2 package be present"
      apt:
        name=apache2
        update_cache=yes
        state=present
      notify:
        - restart apache2

    - name: "Ensure apache2 is running (and enable it at boot)"
      service: name=apache2 state=started enabled=yes

    - name: "Modify html file"
      command: echo "<h1>Hostname {{ inventory_hostname }} ({{ ansible_eth0.ipv4.address }})</h1> >> /var/www/html/ index.html"
