---
- hosts: all-test

  handlers:
    - name: "restart rsyslog"
      become: true
      service: name=rsyslog state=restarted

  tasks:
    - name: "Ensure default packages are present"
      apt:
        name={{ item }}
        state=present
        update_cache=yes
      with_items:
        - openssh-server
        - nano
        - sudo
        - ntp
        - rsyslog
        - curl

    - name: "Add admin group"
      group:
        name=admin
        state=present

    - name: "Add admin user"
      user:
        state=present
        name=admin
        group=admin
        comment="Admin user created by ansible"
        groups=sudo
        append=yes
        createhome=no

    - name: "Copy ssh keys to authorized_keys"
      become: true
      authorized_key: user=root key="{{ lookup('file', '{{ item }}') }}"
      with_fileglob:
        - group_files/ssh/keys/*

    - name: "Copy rsyslog configuration"
      template:
        src=group_files/rsyslog/rsyslog.d-90-graylog2.conf.j2
        dest=/etc/rsyslog.d/90-graylog2.conf
      notify:
        - restart rsyslog

    - name: Add mappings to /etc/hosts
      blockinfile:
        dest: /etc/hosts
        block: |
          {{item.ip}} {{item.name}}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{item.name}}"
      with_items:
          - { name: node1, ip: 192.169.2.111 }
          - { name: node2, ip: 192.169.2.112 }
          - { name: node3, ip: 192.169.2.113 }
          - { name: node4, ip: 192.169.2.114 }
          - { name: node5, ip: 192.169.2.115 }
          - { name: web1, ip: 192.169.2.101 }
          - { name: web2, ip: 192.169.2.102 }
          - { name: haproxy, ip: 192.169.2.100 }
          - { name: graylog, ip: 192.169.2.102 }
