---
- hosts: all
  vars:
  tasks:
    - name: "Ensure default packages are present"
      apt:
        name={{ item }}
        state=present
        update_cache=yes
      with_items:
        - openssh-server
        - nano
        - sudo
        - ntp
