---
- hosts: haproxy
  handlers:
    - name: "restart haproxy"
      service: name=haproxy state=restarted

  tasks:
    - name: "Ensure haproxy package be present"
      apt:
        name=haproxy
        update_cache=yes
        state=present

    - name: "Rename original haproxy config file"
      command: mv /etc/haproxy/haproxy.cfg{,.original}

    - name: "Recreate basic haproxy config file"
      template:
        src=files/haproxy/haproxy.cfg
        dest=/etc/haproxy/haproxy.cfg
      notify:
        - restart haproxy

    - name: "Ensure haproxy is running (and enable it at boot)"
      service: name=haproxy state=started enabled=yes
