---
- hosts: all
  tasks:

    - name: "Add admin group"
      group:
        name=admin
        state=present


    - name: "Add admin user"
      user:
        state=present
        name=admin
        group=admin
        comment="Admin user"
        groups=sudo
        append=yes
        createhome=no
